version: "3"
services:  
  server:
    build:
      context: .
      dockerfile: DockerFile.server
    image: ilovelili/geo-server
    restart: always   
  client:
    build:
      context: .
      dockerfile: DockerFile.client
    image: ilovelili/geo-client
    restart: always
    links:
      - server
    ports:
      - "4200:4200"